/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeliverResponse {
    #[serde(rename = "schema_version", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<String>,
    /// Unique request identifier
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// Total recipients submitted
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of recipients accepted for delivery
    #[serde(rename = "accepted", skip_serializing_if = "Option::is_none")]
    pub accepted: Option<i32>,
    /// Recipients that were rejected (suppressed or failed validation)
    #[serde(rename = "rejected", skip_serializing_if = "Option::is_none")]
    pub rejected: Option<Vec<models::BatchDeliverResponseRejectedInner>>,
    /// Batch status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "delivery", skip_serializing_if = "Option::is_none")]
    pub delivery: Option<Box<models::BatchDeliverResponseDelivery>>,
}

impl BatchDeliverResponse {
    pub fn new() -> BatchDeliverResponse {
        BatchDeliverResponse {
            schema_version: None,
            request_id: None,
            total: None,
            accepted: None,
            rejected: None,
            status: None,
            delivery: None,
        }
    }
}
/// Batch status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "all_rejected")]
    AllRejected,
}

impl Default for Status {
    fn default() -> Status {
        Self::Queued
    }
}

