/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchDeliverResponseDelivery : Delivery routing info (present when status is queued)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeliverResponseDelivery {
    /// IP pool used
    #[serde(rename = "pool", skip_serializing_if = "Option::is_none")]
    pub pool: Option<String>,
    /// Delivery lane (green or yellow)
    #[serde(rename = "lane", skip_serializing_if = "Option::is_none")]
    pub lane: Option<String>,
    /// Timestamp when batch was queued
    #[serde(rename = "queued_at", skip_serializing_if = "Option::is_none")]
    pub queued_at: Option<String>,
}

impl BatchDeliverResponseDelivery {
    /// Delivery routing info (present when status is queued)
    pub fn new() -> BatchDeliverResponseDelivery {
        BatchDeliverResponseDelivery {
            pool: None,
            lane: None,
            queued_at: None,
        }
    }
}

