/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchDeliverRequest : Same fields as DeliverRequest but 'to' accepts up to 100 recipients.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeliverRequest {
    /// List of recipient email addresses (max 100)
    #[serde(rename = "to")]
    pub to: Vec<String>,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "domain_id")]
    pub domain_id: String,
    #[serde(rename = "reply_to", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<String>,
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "campaign_type", skip_serializing_if = "Option::is_none")]
    pub campaign_type: Option<String>,
    #[serde(rename = "structured_data", skip_serializing_if = "Option::is_none")]
    pub structured_data: Option<Box<models::BatchDeliverRequestStructuredData>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<serde_json::Value>,
}

impl BatchDeliverRequest {
    /// Same fields as DeliverRequest but 'to' accepts up to 100 recipients.
    pub fn new(to: Vec<String>, from: String, subject: String, domain_id: String) -> BatchDeliverRequest {
        BatchDeliverRequest {
            to,
            from,
            subject,
            html: None,
            text: None,
            domain_id,
            reply_to: None,
            headers: None,
            tags: None,
            campaign_type: None,
            structured_data: None,
            options: None,
        }
    }
}

