/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateJobRequest : Bulk jobs use the account's default validation policy. To use a specific policy, set it as default via the Policies API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJobRequest {
    /// List of emails to validate
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
    /// Remove duplicate emails
    #[serde(rename = "dedup", skip_serializing_if = "Option::is_none")]
    pub dedup: Option<bool>,
    /// Custom metadata for the job
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// URL for completion webhook
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
    /// Unique key for idempotent requests
    #[serde(rename = "idempotency_key", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
}

impl CreateJobRequest {
    /// Bulk jobs use the account's default validation policy. To use a specific policy, set it as default via the Policies API.
    pub fn new(emails: Vec<String>) -> CreateJobRequest {
        CreateJobRequest {
            emails,
            dedup: None,
            metadata: None,
            webhook_url: None,
            idempotency_key: None,
        }
    }
}

