/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateListRequest {
    /// List name (unique per account)
    #[serde(rename = "name")]
    pub name: String,
    /// Optional list description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// URL to redirect subscribers after confirmation
    #[serde(rename = "confirmation_redirect_url", skip_serializing_if = "Option::is_none")]
    pub confirmation_redirect_url: Option<String>,
    /// Custom confirmation email subject
    #[serde(rename = "confirmation_subject", skip_serializing_if = "Option::is_none")]
    pub confirmation_subject: Option<String>,
    /// Custom sender name for confirmation emails
    #[serde(rename = "confirmation_from_name", skip_serializing_if = "Option::is_none")]
    pub confirmation_from_name: Option<String>,
}

impl CreateListRequest {
    pub fn new(name: String) -> CreateListRequest {
        CreateListRequest {
            name,
            description: None,
            confirmation_redirect_url: None,
            confirmation_subject: None,
            confirmation_from_name: None,
        }
    }
}

