/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliverRequest {
    /// List of recipient email addresses
    #[serde(rename = "to")]
    pub to: Vec<models::DeliverRequestToInner>,
    /// Sender email address (must match sending domain)
    #[serde(rename = "from")]
    pub from: String,
    /// Email subject line
    #[serde(rename = "subject")]
    pub subject: String,
    /// HTML email body
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    /// Plain text email body
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Sending domain UUID
    #[serde(rename = "domain_id")]
    pub domain_id: String,
    /// Reply-to address
    #[serde(rename = "reply_to", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<String>,
    /// Extra email headers
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
    /// Tags for categorization
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Campaign type for JSON-LD auto-generation
    #[serde(rename = "campaign_type", skip_serializing_if = "Option::is_none")]
    pub campaign_type: Option<CampaignType>,
    #[serde(rename = "structured_data", skip_serializing_if = "Option::is_none")]
    pub structured_data: Option<Box<models::DeliverRequestStructuredData>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::DeliverRequestOptions>>,
}

impl DeliverRequest {
    pub fn new(to: Vec<models::DeliverRequestToInner>, from: String, subject: String, domain_id: String) -> DeliverRequest {
        DeliverRequest {
            to,
            from,
            subject,
            html: None,
            text: None,
            domain_id,
            reply_to: None,
            headers: None,
            tags: None,
            campaign_type: None,
            structured_data: None,
            options: None,
        }
    }
}
/// Campaign type for JSON-LD auto-generation
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CampaignType {
    #[serde(rename = "order_confirmation")]
    OrderConfirmation,
    #[serde(rename = "shipping_notification")]
    ShippingNotification,
    #[serde(rename = "subscription_confirm")]
    SubscriptionConfirm,
    #[serde(rename = "review_request")]
    ReviewRequest,
    #[serde(rename = "event_invitation")]
    EventInvitation,
    #[serde(rename = "promotional")]
    Promotional,
    #[serde(rename = "welcome")]
    Welcome,
    #[serde(rename = "password_reset")]
    PasswordReset,
    #[serde(rename = "appointment_reminder")]
    AppointmentReminder,
    #[serde(rename = "ticket_confirmation")]
    TicketConfirmation,
}

impl Default for CampaignType {
    fn default() -> CampaignType {
        Self::OrderConfirmation
    }
}

