/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSendingStats200ResponseStats {
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(rename = "sent", skip_serializing_if = "Option::is_none")]
    pub sent: Option<i32>,
    #[serde(rename = "delivered", skip_serializing_if = "Option::is_none")]
    pub delivered: Option<i32>,
    #[serde(rename = "bounced", skip_serializing_if = "Option::is_none")]
    pub bounced: Option<i32>,
    #[serde(rename = "deferred", skip_serializing_if = "Option::is_none")]
    pub deferred: Option<i32>,
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<i32>,
    #[serde(rename = "opened_total", skip_serializing_if = "Option::is_none")]
    pub opened_total: Option<i32>,
    #[serde(rename = "opened_unique", skip_serializing_if = "Option::is_none")]
    pub opened_unique: Option<i32>,
    #[serde(rename = "clicked_total", skip_serializing_if = "Option::is_none")]
    pub clicked_total: Option<i32>,
    #[serde(rename = "clicked_unique", skip_serializing_if = "Option::is_none")]
    pub clicked_unique: Option<i32>,
    #[serde(rename = "unsubscribed", skip_serializing_if = "Option::is_none")]
    pub unsubscribed: Option<i32>,
    #[serde(rename = "delivery_rate", skip_serializing_if = "Option::is_none")]
    pub delivery_rate: Option<f64>,
    #[serde(rename = "open_rate", skip_serializing_if = "Option::is_none")]
    pub open_rate: Option<f64>,
    #[serde(rename = "click_rate", skip_serializing_if = "Option::is_none")]
    pub click_rate: Option<f64>,
    /// Opens from known bots/scanners
    #[serde(rename = "bot_opens", skip_serializing_if = "Option::is_none")]
    pub bot_opens: Option<i32>,
    /// Verified human opens
    #[serde(rename = "human_opens", skip_serializing_if = "Option::is_none")]
    pub human_opens: Option<i32>,
    /// Percentage of opens from bots
    #[serde(rename = "bot_open_pct", skip_serializing_if = "Option::is_none")]
    pub bot_open_pct: Option<f64>,
}

impl GetSendingStats200ResponseStats {
    pub fn new() -> GetSendingStats200ResponseStats {
        GetSendingStats200ResponseStats {
            period: None,
            sent: None,
            delivered: None,
            bounced: None,
            deferred: None,
            failed: None,
            opened_total: None,
            opened_unique: None,
            clicked_total: None,
            clicked_unique: None,
            unsubscribed: None,
            delivery_rate: None,
            open_rate: None,
            click_rate: None,
            bot_opens: None,
            human_opens: None,
            bot_open_pct: None,
        }
    }
}

