/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendingDomain {
    /// Domain UUID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Domain name
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Domain type (ns_delegated)
    #[serde(rename = "domain_type", skip_serializing_if = "Option::is_none")]
    pub domain_type: Option<String>,
    /// Domain verification status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// DKIM selector (e.g. mo1)
    #[serde(rename = "dkim_selector", skip_serializing_if = "Option::is_none")]
    pub dkim_selector: Option<String>,
    #[serde(rename = "dns_records", skip_serializing_if = "Option::is_none")]
    pub dns_records: Option<Box<models::SendingDomainDnsRecords>>,
    /// BIMI SVG logo URL
    #[serde(rename = "bimi_svg_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bimi_svg_url: Option<Option<String>>,
    /// BIMI VMC certificate URL
    #[serde(rename = "bimi_vmc_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bimi_vmc_url: Option<Option<String>>,
    /// Whether BIMI is enabled
    #[serde(rename = "bimi_enabled", skip_serializing_if = "Option::is_none")]
    pub bimi_enabled: Option<bool>,
    /// Reply forwarding address
    #[serde(rename = "forward_replies_to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub forward_replies_to: Option<Option<String>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl SendingDomain {
    pub fn new() -> SendingDomain {
        SendingDomain {
            id: None,
            domain: None,
            domain_type: None,
            status: None,
            dkim_selector: None,
            dns_records: None,
            bimi_svg_url: None,
            bimi_vmc_url: None,
            bimi_enabled: None,
            forward_replies_to: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// Domain verification status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending_dns")]
    PendingDns,
    #[serde(rename = "dns_partial")]
    DnsPartial,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
}

impl Default for Status {
    fn default() -> Status {
        Self::PendingDns
    }
}

