/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscribeRequest {
    /// Subscriber email address
    #[serde(rename = "email")]
    pub email: String,
    /// Subscriber name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Custom metadata key-value pairs
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// URL of the page where the subscription form was submitted (for consent proof)
    #[serde(rename = "page_url", skip_serializing_if = "Option::is_none")]
    pub page_url: Option<String>,
    /// Identifier of the form used to subscribe (for consent proof)
    #[serde(rename = "form_id", skip_serializing_if = "Option::is_none")]
    pub form_id: Option<String>,
}

impl SubscribeRequest {
    pub fn new(email: String) -> SubscribeRequest {
        SubscribeRequest {
            email,
            name: None,
            metadata: None,
            page_url: None,
            form_id: None,
        }
    }
}

