/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriberList {
    /// List UUID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Account ID
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<i32>,
    /// List name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// List description
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// Redirect URL after confirmation
    #[serde(rename = "confirmation_redirect_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub confirmation_redirect_url: Option<Option<String>>,
    /// Confirmation email subject
    #[serde(rename = "confirmation_subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub confirmation_subject: Option<Option<String>>,
    /// Confirmation email sender name
    #[serde(rename = "confirmation_from_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub confirmation_from_name: Option<Option<String>>,
    /// Total subscriber count
    #[serde(rename = "subscriber_count", skip_serializing_if = "Option::is_none")]
    pub subscriber_count: Option<i32>,
    /// Confirmed subscriber count
    #[serde(rename = "confirmed_count", skip_serializing_if = "Option::is_none")]
    pub confirmed_count: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl SubscriberList {
    pub fn new() -> SubscriberList {
        SubscriberList {
            id: None,
            account_id: None,
            name: None,
            description: None,
            confirmation_redirect_url: None,
            confirmation_subject: None,
            confirmation_from_name: None,
            subscriber_count: None,
            confirmed_count: None,
            created_at: None,
            updated_at: None,
        }
    }
}

