/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TelemetrySummary : Validation metrics for building dashboards and monitoring.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TelemetrySummary {
    #[serde(rename = "schemaVersion", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<String>,
    #[serde(rename = "window", skip_serializing_if = "Option::is_none")]
    pub window: Option<Window>,
    #[serde(rename = "generatedAt", skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<String>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    #[serde(rename = "totals", skip_serializing_if = "Option::is_none")]
    pub totals: Option<Box<models::TelemetrySummaryTotals>>,
    #[serde(rename = "rates", skip_serializing_if = "Option::is_none")]
    pub rates: Option<Box<models::TelemetrySummaryRates>>,
    /// Top rejection/status reasons
    #[serde(rename = "topReasons", skip_serializing_if = "Option::is_none")]
    pub top_reasons: Option<Vec<models::TelemetrySummaryTopReasonsInner>>,
    /// Top domains by volume
    #[serde(rename = "topDomains", skip_serializing_if = "Option::is_none")]
    pub top_domains: Option<Vec<models::TelemetrySummaryTopDomainsInner>>,
}

impl TelemetrySummary {
    /// Validation metrics for building dashboards and monitoring.
    pub fn new() -> TelemetrySummary {
        TelemetrySummary {
            schema_version: None,
            window: None,
            generated_at: None,
            timezone: None,
            totals: None,
            rates: None,
            top_reasons: None,
            top_domains: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Window {
    #[serde(rename = "1h")]
    Variant1h,
    #[serde(rename = "24h")]
    Variant24h,
    #[serde(rename = "30d")]
    Variant30d,
}

impl Default for Window {
    fn default() -> Window {
        Self::Variant1h
    }
}

