/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidationResponse : Flat validation response. Conditional fields are omitted (not null) when not applicable.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationResponse {
    #[serde(rename = "schema_version")]
    pub schema_version: String,
    #[serde(rename = "email")]
    pub email: String,
    /// Validation status
    #[serde(rename = "status")]
    pub status: Status,
    /// Recommended action
    #[serde(rename = "action")]
    pub action: Action,
    /// Detailed status reason. Omitted when none.
    #[serde(rename = "sub_status", skip_serializing_if = "Option::is_none")]
    pub sub_status: Option<SubStatus>,
    #[serde(rename = "domain")]
    pub domain: String,
    /// Whether MX records were found for the domain
    #[serde(rename = "mx_found")]
    pub mx_found: bool,
    /// Primary MX hostname. Omitted when MX not resolved.
    #[serde(rename = "mx_host", skip_serializing_if = "Option::is_none")]
    pub mx_host: Option<String>,
    /// Whether SMTP verification passed. Omitted when SMTP not checked.
    #[serde(rename = "smtp_check", skip_serializing_if = "Option::is_none")]
    pub smtp_check: Option<bool>,
    /// Whether domain is catch-all. Omitted when SMTP not checked.
    #[serde(rename = "catch_all", skip_serializing_if = "Option::is_none")]
    pub catch_all: Option<bool>,
    /// Whether domain is a known disposable email provider
    #[serde(rename = "disposable")]
    pub disposable: bool,
    /// Whether address is a role account (e.g., info@, admin@)
    #[serde(rename = "role_account")]
    pub role_account: bool,
    /// Whether domain is a known free email provider (e.g., gmail.com)
    #[serde(rename = "free_provider")]
    pub free_provider: bool,
    /// Validation depth used for this check
    #[serde(rename = "depth")]
    pub depth: Depth,
    /// ISO 8601 timestamp of validation
    #[serde(rename = "processed_at")]
    pub processed_at: String,
    /// Typo correction suggestion. Omitted when no typo detected.
    #[serde(rename = "suggested_email", skip_serializing_if = "Option::is_none")]
    pub suggested_email: Option<String>,
    /// Suggested retry delay in milliseconds. Present only for retry_later action.
    #[serde(rename = "retry_after_ms", skip_serializing_if = "Option::is_none")]
    pub retry_after_ms: Option<i32>,
    #[serde(rename = "suppression_match", skip_serializing_if = "Option::is_none")]
    pub suppression_match: Option<Box<models::ValidationResponseSuppressionMatch>>,
    #[serde(rename = "policy_applied", skip_serializing_if = "Option::is_none")]
    pub policy_applied: Option<Box<models::ValidationResponsePolicyApplied>>,
}

impl ValidationResponse {
    /// Flat validation response. Conditional fields are omitted (not null) when not applicable.
    pub fn new(schema_version: String, email: String, status: Status, action: Action, domain: String, mx_found: bool, disposable: bool, role_account: bool, free_provider: bool, depth: Depth, processed_at: String) -> ValidationResponse {
        ValidationResponse {
            schema_version,
            email,
            status,
            action,
            sub_status: None,
            domain,
            mx_found,
            mx_host: None,
            smtp_check: None,
            catch_all: None,
            disposable,
            role_account,
            free_provider,
            depth,
            processed_at,
            suggested_email: None,
            retry_after_ms: None,
            suppression_match: None,
            policy_applied: None,
        }
    }
}
/// Validation status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "valid")]
    Valid,
    #[serde(rename = "invalid")]
    Invalid,
    #[serde(rename = "catch_all")]
    CatchAll,
    #[serde(rename = "do_not_mail")]
    DoNotMail,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Valid
    }
}
/// Recommended action
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "accept_with_caution")]
    AcceptWithCaution,
    #[serde(rename = "reject")]
    Reject,
    #[serde(rename = "retry_later")]
    RetryLater,
}

impl Default for Action {
    fn default() -> Action {
        Self::Accept
    }
}
/// Detailed status reason. Omitted when none.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubStatus {
    #[serde(rename = "format_invalid")]
    FormatInvalid,
    #[serde(rename = "mx_missing")]
    MxMissing,
    #[serde(rename = "mx_timeout")]
    MxTimeout,
    #[serde(rename = "smtp_unreachable")]
    SmtpUnreachable,
    #[serde(rename = "smtp_rejected")]
    SmtpRejected,
    #[serde(rename = "disposable")]
    Disposable,
    #[serde(rename = "role_account")]
    RoleAccount,
    #[serde(rename = "greylisted")]
    Greylisted,
    #[serde(rename = "catch_all_detected")]
    CatchAllDetected,
    #[serde(rename = "suppression_match")]
    SuppressionMatch,
}

impl Default for SubStatus {
    fn default() -> SubStatus {
        Self::FormatInvalid
    }
}
/// Validation depth used for this check
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Depth {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "enhanced")]
    Enhanced,
}

impl Default for Depth {
    fn default() -> Depth {
        Self::Standard
    }
}

