/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationResponse {
    #[serde(rename = "schema_version", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<String>,
    #[serde(rename = "email")]
    pub email: String,
    /// Validation status
    #[serde(rename = "status")]
    pub status: Status,
    /// Detailed status reason
    #[serde(rename = "sub_status", skip_serializing_if = "Option::is_none")]
    pub sub_status: Option<String>,
    /// Recommended action
    #[serde(rename = "action")]
    pub action: Action,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "mx_found", skip_serializing_if = "Option::is_none")]
    pub mx_found: Option<bool>,
    #[serde(rename = "smtp_check", skip_serializing_if = "Option::is_none")]
    pub smtp_check: Option<bool>,
    #[serde(rename = "disposable", skip_serializing_if = "Option::is_none")]
    pub disposable: Option<bool>,
    #[serde(rename = "role_account", skip_serializing_if = "Option::is_none")]
    pub role_account: Option<bool>,
    #[serde(rename = "free_provider", skip_serializing_if = "Option::is_none")]
    pub free_provider: Option<bool>,
    #[serde(rename = "suppression_match", skip_serializing_if = "Option::is_none")]
    pub suppression_match: Option<Box<models::ValidationResponseSuppressionMatch>>,
}

impl ValidationResponse {
    pub fn new(email: String, status: Status, action: Action) -> ValidationResponse {
        ValidationResponse {
            schema_version: None,
            email,
            status,
            sub_status: None,
            action,
            domain: None,
            mx_found: None,
            smtp_check: None,
            disposable: None,
            role_account: None,
            free_provider: None,
            suppression_match: None,
        }
    }
}
/// Validation status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "valid")]
    Valid,
    #[serde(rename = "invalid")]
    Invalid,
    #[serde(rename = "catch_all")]
    CatchAll,
    #[serde(rename = "do_not_mail")]
    DoNotMail,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Valid
    }
}
/// Recommended action
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "accept_with_caution")]
    AcceptWithCaution,
    #[serde(rename = "reject")]
    Reject,
    #[serde(rename = "retry_later")]
    RetryLater,
}

impl Default for Action {
    fn default() -> Action {
        Self::Accept
    }
}

